# syntax=docker/dockerfile:1
#
# Final artifact stage. Pulls the WPE final-resume image, the GTK
# final-resume image, and the source-prep image (for pw_run.sh), composes
# them into a single FROM-scratch artifact at /webkit.
#
# The result matches PW's published webkit-*.zip layout:
#   /webkit/
#     minibrowser-wpe/   (from WPE chain)
#     minibrowser-gtk/   (from GTK chain)
#     pw_run.sh          (from source-prep, copied verbatim from PW)

ARG BASE_WPE
ARG BASE_GTK
ARG BASE_SOURCE

FROM ${BASE_WPE} AS wpe
FROM ${BASE_GTK} AS gtk
FROM ${BASE_SOURCE} AS source

# Patch pw_run.sh to export WEBKIT_EXEC_PATH so WebKit's ProcessLauncher
# finds aux processes (WPENetworkProcess, etc) alongside MiniBrowser instead
# of the compile-time PKGLIBEXECDIR (/usr/libexec/wpe-webkit-2.0/) which we
# don't ship.
FROM ${BASE_SOURCE} AS pw_run_patched
RUN sed -i 's|WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER"|WEBKIT_EXEC_PATH="$SCRIPT_PATH/$MINIBROWSER_FOLDER" WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER"|' \
    /work/pw-webkit/pw_run.sh

FROM scratch AS artifact
COPY --from=wpe /work/minibrowser-wpe-dist /webkit/minibrowser-wpe
COPY --from=gtk /work/minibrowser-gtk-dist /webkit/minibrowser-gtk
COPY --from=pw_run_patched /work/pw-webkit/pw_run.sh /webkit/pw_run.sh
