#!/usr/bin/env node
/*
 * Emits the PGO training corpus this branch appends to Mozilla's own
 * (build/pgo/index.html). Both pages are generated from playwright/bench/
 * runtime-probe.cjs so the thing the profile is trained on and the thing the
 * perf gate grades are the same source, not two copies that drift.
 *
 * Regenerate after any runtime-probe.cjs change:
 *   node playwright/alpine-browsers/firefox/pgo-corpus/build-corpus.cjs
 *
 * Only the in-page kernels can be trained on. launch, context_page,
 * screenshot, click_force, locator_click and eval_rtt are CDP/process-level
 * and no page a profileserver opens with window.open can reach them — so this
 * corpus deliberately covers a subset of the graded rows, and cannot move the
 * ones it does not cover.
 */
const fs = require('fs');
const path = require('path');

const { PAGE_HTML, KERNELS } = require('../../../bench/runtime-probe.cjs');

/*
 * tally's `control` group — int_math and libm_fmod — is excluded on purpose.
 * Those rows exist to be unmovable by codegen, and firefox's PGO result is
 * believable precisely because they stayed pinned at 0.86 while the rest fell
 * to 0.74. Feeding them to the profile would spend the only negative control
 * this experiment has.
 */
const CONTROL_KERNELS = ['int_math', 'libm_fmod'];

// One probe.html load runs every trained kernel ROUNDS times; index.html
// reloads it NAVS times so the parse+load path the goto rows measure is
// trained too. NAVS * the per-load cap below stays under profileserver's
// 2-minute extendedTimeout even if every load wedges, and an instrumented
// build runs several times slower than a shipped one.
const ROUNDS = 3;
const NAVS = 8;
const LOAD_CAP_MS = 8000;

const GENERATED = `<!-- GENERATED by pgo-corpus/build-corpus.cjs from playwright/bench/runtime-probe.cjs — do not edit -->`;

const trainedKernels = Object.entries(KERNELS).filter(
  ([name]) => !CONTROL_KERNELS.includes(name)
);
if (!trainedKernels.length) {
  throw new Error('every kernel was filtered out as a control — check CONTROL_KERNELS');
}

const kernelEntries = trainedKernels
  .map(([name, body]) => `  ${JSON.stringify(name)}: ${body},`)
  .join('\n');

const driverScript = `<script>
const KERNELS = {
${kernelEntries}
};

// Kernels return the milliseconds they measured; nothing here reads that back.
// The point is to execute the code, not to time it — the perf gate does the
// timing, on a build compiled from the profile this run produces.
async function runRounds() {
  for (let round = 0; round < ${ROUNDS}; round++) {
    for (const name of Object.keys(KERNELS)) {
      await KERNELS[name]();
    }
  }
  document.title = 'probe-done';
}
window.addEventListener('load', runRounds);
</script>`;

const probeHtml = `${GENERATED}\n${PAGE_HTML.replace('</body></html>', `${driverScript}\n</body></html>`)}\n`;

const indexHtml = `${GENERATED}
<!doctype html>
<html><head><meta charset="utf-8"><title>probe corpus</title></head><body>
<iframe id="probe" width="1024" height="768"></iframe>
<script>
  // Re-navigating the frame rather than looping in place: a reload walks the
  // parser, the style resolver and the loader, which is the path goto_cold and
  // goto_warm are graded on. Staying on one document would train neither.
  let nav = 0;

  function nextNav() {
    if (nav >= ${NAVS}) {
      document.title = 'corpus-done';
      return;
    }
    nav++;
    document.getElementById('probe').src = 'probe.html?nav=' + nav;
  }

  document.getElementById('probe').addEventListener('load', () => {
    const frame = document.getElementById('probe').contentDocument;
    if (!frame) {
      nextNav();
      return;
    }
    // The frame sets its own title when its rounds finish; poll rather than
    // race it, and move on regardless after a bounded wait so one wedged load
    // cannot eat the whole profileserver timeout.
    let waited = 0;
    const poll = setInterval(() => {
      waited += 100;
      if (frame.title === 'probe-done' || waited > ${LOAD_CAP_MS}) {
        clearInterval(poll);
        nextNav();
      }
    }, 100);
  });

  nextNav();
</script>
</body></html>
`;

const outDir = __dirname;
fs.writeFileSync(path.join(outDir, 'probe.html'), probeHtml);
fs.writeFileSync(path.join(outDir, 'index.html'), indexHtml);
console.log(`wrote probe.html (${probeHtml.length} B) and index.html (${indexHtml.length} B)`);
console.log(`kernels trained: ${trainedKernels.map(([n]) => n).join(', ')}`);
console.log(`kernels held out as controls: ${CONTROL_KERNELS.join(', ')}`);
